class AppGetterName {
  /// GET all region from Indonesia
  static const String region = "Indonesia";
  static const String aceh = 'Aceh';
  static const String bali = 'Bali';
  static const String bangkaBelitung = 'BangkaBelitung';
  static const String banten = 'Banten';
  static const String bengkulu = 'Bengkulu';
  static const String dIYogyakarta = 'DIYogyakarta';
  static const String dKIJakarta = 'DKIJakarta';
  static const String gorontalo = 'Gorontalo';
  static const String jambi = 'Jambi';
  static const String jawaBarat = 'JawaBarat';
  static const String jawaTengah = 'JawaTengah';
  static const String jawaTimur = 'JawaTimur';
  static const String kalimantanBarat = 'KalimantanBarat';
  static const String kalimantanSelatan = 'KalimantanSelatan';
  static const String kalimantanTengah = 'KalimantanTengah';
  static const String kalimantanTimur = 'KalimantanTimur';
  static const String kalimantanUtara = 'KalimantanUtara';
  static const String kepulauanRiau = 'KepulauanRiau';
  static const String lampung = 'Lampung';
  static const String maluku = 'Maluku';
  static const String malukuUtara = 'MalukuUtara';
  static const String nusaTenggaraBarat = 'NusaTenggaraBarat';
  static const String nusaTenggaraTimur = 'NusaTenggaraTimur';
  static const String papua = 'Papua';
  static const String papuaBarat = 'PapuaBarat';
  static const String riau = 'Riau';
  static const String sulawesiBarat = 'SulawesiBarat';
  static const String sulawesiSelatan = 'SulawesiSelatan';
  static const String sulawesiTengah = 'SulawesiTengah';
  static const String sulawesiTenggara = 'SulawesiTenggara';
  static const String sulawesiUtara = 'SulawesiUtara';
  static const String sumateraBarat = 'SumateraBarat';
  static const String sumateraSelatan = 'SumateraSelatan';
  static const String sumateraUtara = 'SumateraUtara';
}
